import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Button from "@/components/Button";
import Header from "@/components/Header";
import { Suspense } from "react";
import AuthProvider from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AuthProvider>

          <div className="grid grid-rows-[auto_1fr_auto] min-h-dvh">
            <Suspense fallback={<div className="h-20 bg-transparent" />}>
              <Header />
            </Suspense>
            {children}

            <footer className="w-full h-20 bg-[var(--color-dark)] flex items-center justify-center md:justify-start">
              <p className="ml-6 text-center">© 2025 Digital Money House</p>
            </footer>
          </div>
        </AuthProvider>

      </body>
    </html>
  );
}
